### ISSUE TITLE
Should empty intersection be simplified?

### ISSUE THREAD

**Issue by NeilGirdhar** [CarliJoy/intersection_examples#20]
@randolf-scholz requests this here: https://github.com/CarliJoy/intersection_examples/issues/10#issuecomment-1657071906

If so, it should be added to the reductions.

**Comment by NeilGirdhar** [comment]
Linking @kmillikin's [prescient comment](https://github.com/CarliJoy/intersection_examples/issues/10#issuecomment-1665870871).

**Comment by mniip** [comment]
Most people seemed to agree that if it should reduce then it should reduce to `object` or an empty Protocol, which is the opposite of `Never`.

**Comment by NeilGirdhar** [comment]
Yes, `Never` seems reasonable to me.  Whatever we think it is, this issue is more about whether that reduction should be mandated or not.

**Comment by randolf-scholz** [comment]
It's either `object`, or one could consider creating a `typing.Top` which would be an empty `Protocol`.
The latter might be advantageous, because which `Top` would match everything just like `object`, `type[object]` does not match `Protocol`. 

This makes a difference, for instance in the `merge_protocols` function I presented:

```python
from typing import TypeVarTuple, Intersection

protocols = TypeVarTuple("protocols")   
# technically we want TypeVarTuple("protocols", bound=type[Protocol])
# but bounds are not supported yet for TypeVarTuple.

def merge_protocols(*protos: *protocols) -> Intersection[*Protocols]: ...
    """Creates the intersection of pairwise disjoint protocol classes."""
    # if intersection is empty, returns a protocol that matches with any class.
    # Note: https://peps.python.org/pep-0646/#args-as-a-type-variable-tuple
```

Here, one would expect that this function can be chained with itself. But, for instance, consider what happens in the case of `merge_protocols(merge_protocols())`: If `merge_protocols()` returns `object`, then this would raise a type-error, since `type[object]` is not a subtype of `type[Protocol]`.

This shows that it makes a difference whether `object` or an empty `Protocol` is identified with `Intersection[()]`.

**Comment by mikeshardmind** [comment]
I would rather not treat empty intersections as object/any/typing.Top and just use the existing subtype rules "is it a subtype of all of these"? if it is empty, yes. The pragmatism of this is shown with TypeVarTuples. No special case or reduction needed here.

**Comment by randolf-scholz** [comment]
Just noticed an issue with this whole example, which is that currently PEP544 makes it impossible to type hint functions that return actual `Protocol` classes, since _"Variables and parameters annotated with Type[Proto] accept only concrete (non-protocol) subtypes of Proto."_ https://github.com/python/typing/issues/1441

**Comment by mikeshardmind** [comment]
Another reason to just leave empty intersection as empty intersection then

**Comment by NeilGirdhar** [comment]
@randolf-scholz Can we close this as not added to the specification?

**Comment by randolf-scholz** [comment]
Sure.
